import React, { useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import mermaid from 'mermaid';
import { Download, Share2, Edit, ExternalLink } from 'lucide-react';

const BlueprintView = ({ blueprint }) => {

    useEffect(() => {
        if (blueprint) {
            mermaid.initialize({ startOnLoad: true, theme: 'dark', securityLevel: 'loose' });
            setTimeout(() => {
                mermaid.contentLoaded();
            }, 500);
        }
    }, [blueprint]);

    if (!blueprint) return null;

    // Extract Mermaid code if present
    const mermaidMatch = blueprint.match(/```mermaid([\s\S]*?)```/);
    let mermaidCode = mermaidMatch ? mermaidMatch[1].trim() : null;

    // Aggressive Cleanup: Find the start of the graph definition
    if (mermaidCode) {
        // Remove any potential "mermaid" text identifier that wasn't caught
        mermaidCode = mermaidCode.replace(/^mermaid\s*/i, '');

        // Find the 'graph' keyword and start from there if present
        const graphStart = mermaidCode.indexOf('graph');
        if (graphStart !== -1) {
            mermaidCode = mermaidCode.substring(graphStart);
            console.log("Rendered Mermaid Code:", mermaidCode); // Debugging
        }
    }

    const cleanBlueprint = blueprint.replace(/```mermaid[\s\S]*?```/, '');

    const openDrawIo = () => {
        window.open('https://app.diagrams.net/', '_blank');
    };

    const handleShare = async () => {
        if (navigator.share) {
            try {
                await navigator.share({
                    title: 'My AI Project Blueprint',
                    text: 'Check out this project idea generated by AI!',
                    url: window.location.href,
                });
            } catch (error) {
                console.log('Error sharing', error);
            }
        } else {
            // Fallback to clipboard
            navigator.clipboard.writeText(blueprint).then(() => {
                alert('Blueprint copied to clipboard!');
            });
        }
    };

    const handleDownload = () => {
        const element = document.createElement("a");
        const file = new Blob([blueprint], { type: 'text/markdown' });
        element.href = URL.createObjectURL(file);
        element.download = "project_blueprint.md";
        document.body.appendChild(element); // Required for this to work in FireFox
        element.click();
        document.body.removeChild(element);
    };

    return (
        <div className="w-full max-w-4xl mx-auto bg-slate-800 p-8 rounded-xl shadow-2xl border border-slate-700 animate-fade-in mt-10">
            <div className="flex justify-between items-center mb-6 border-b border-slate-700 pb-4">
                <h2 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-blue-500">
                    ✨ Project Blueprint Ready
                </h2>
                <div className="flex space-x-3">
                    <button onClick={openDrawIo} className="flex items-center space-x-2 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 rounded-lg transition-colors text-sm text-white" title="Open Draw.io">
                        <Edit className="h-4 w-4" /> <span>Draw.io</span>
                    </button>
                    <button onClick={handleDownload} className="p-2 bg-slate-700 hover:bg-slate-600 rounded-full transition-colors" title="Download">
                        <Download className="h-5 w-5 text-gray-300" />
                    </button>
                    <button onClick={handleShare} className="p-2 bg-slate-700 hover:bg-slate-600 rounded-full transition-colors" title="Share">
                        <Share2 className="h-5 w-5 text-gray-300" />
                    </button>
                </div>
            </div>

            {mermaidCode && (
                <div className="mb-8 p-4 bg-slate-900 rounded-lg border border-slate-700 overflow-x-auto">
                    <h3 className="text-lg font-semibold text-slate-300 mb-4 flex items-center">
                        <ExternalLink className="h-5 w-5 mr-2 text-blue-400" /> System Architecture
                    </h3>
                    <div className="mermaid flex justify-center">
                        {mermaidCode}
                    </div>
                </div>
            )}

            <div className="prose prose-invert max-w-none">
                <ReactMarkdown>{cleanBlueprint}</ReactMarkdown>
            </div>
        </div>
    );
};

export default BlueprintView;
