import React, { useEffect, useRef, useState, useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import mermaid from 'mermaid';
import { Download, Share2, Edit, ExternalLink, Box, Layers, Code, Zap } from 'lucide-react';
import { motion } from 'framer-motion';
import DeepDiveStats from './DeepDiveStats';
import ExportTools from './ExportTools';

const BlueprintView = ({ blueprint }) => {
    const blueprintRef = useRef(null);
    const [parsedStats, setParsedStats] = useState(null);
    const [cleanMarkdown, setCleanMarkdown] = useState('');
    const [mermaidCode, setMermaidCode] = useState('');

    useEffect(() => {
        if (!blueprint) return;

        // Initialize Mermaid
        mermaid.initialize({
            startOnLoad: true,
            theme: 'dark',
            securityLevel: 'loose',
            fontFamily: 'Inter, sans-serif'
        });

        // 1. Extract JSON Stats Block (usually at the end)
        // Look for ```json ... ``` block
        const jsonRegex = /```json\s*([\s\S]*?)\s*```/;
        const jsonMatch = blueprint.match(jsonRegex);

        let stats = null;
        let markdownContent = blueprint;

        if (jsonMatch) {
            try {
                // Parse the JSON content
                stats = JSON.parse(jsonMatch[1]);
                setParsedStats(stats);

                // Remove the JSON block from the markdown to be displayed
                markdownContent = blueprint.replace(jsonRegex, '');
            } catch (e) {
                console.warn("Could not parse Deep Dive JSON stats:", e);
            }
        }

        // 2. Extract Mermaid Diagram
        const mermaidRegex = /```mermaid([\s\S]*?)```/;
        const mermaidMatch = markdownContent.match(mermaidRegex);
        let mCode = null;

        if (mermaidMatch) {
            mCode = mermaidMatch[1].trim();
            // Cleanup common issues
            mCode = mCode.replace(/^mermaid\s*/i, '');
            const graphStart = mCode.indexOf('graph');
            if (graphStart !== -1) {
                mCode = mCode.substring(graphStart);
            }
            setMermaidCode(mCode);

            // Remove mermaid block from markdown
            markdownContent = markdownContent.replace(mermaidRegex, '');
        } else {
            setMermaidCode(null);
        }

        setCleanMarkdown(markdownContent);

        // Trigger Mermaid render after state updates
        setTimeout(() => {
            mermaid.contentLoaded();
        }, 500);

    }, [blueprint]);

    if (!blueprint) return null;

    const openDrawIo = () => {
        window.open('https://app.diagrams.net/', '_blank');
    };

    // Extract title for export filename
    const getTitle = () => {
        const titleMatch = cleanMarkdown.match(/^#\s+(.*)/m);
        return titleMatch ? titleMatch[1].trim() : 'Project_Blueprint';
    };

    return (
        <div className="w-full max-w-5xl mx-auto space-y-8 animate-fade-in-up">

            {/* Main Blueprint Card */}
            <div ref={blueprintRef} className="bg-slate-900/80 backdrop-blur-xl p-8 rounded-2xl shadow-2xl border border-white/10 relative overflow-hidden group">

                {/* Decorative gradients */}
                <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/10 rounded-full blur-3xl -z-10 group-hover:bg-blue-500/20 transition-all duration-700"></div>

                {/* Header Actions */}
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 border-b border-white/5 pb-6 gap-4">
                    <div className="flex items-center space-x-3">
                        <div className="p-2 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg shadow-lg">
                            <Layers className="text-white w-6 h-6" />
                        </div>
                        <div>
                            <h2 className="text-2xl font-bold text-white tracking-tight">
                                Structural Blueprint
                            </h2>
                            <p className="text-slate-400 text-sm">Generated by AI Architect v2.0</p>
                        </div>
                    </div>

                    <div className="flex flex-wrap gap-2">
                        <button onClick={openDrawIo} className="flex items-center space-x-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 rounded-lg border border-slate-700 transition-all text-sm text-slate-300 hover:text-white hover:border-blue-500/50">
                            <Edit className="h-4 w-4" /> <span>Edit Diagram</span>
                        </button>
                    </div>
                </div>

                {/* Mermaid Diagram Section */}
                {mermaidCode && (
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.2 }}
                        className="mb-10"
                    >
                        <div className="flex items-center mb-4 space-x-2">
                            <Box className="w-5 h-5 text-purple-400" />
                            <h3 className="text-lg font-semibold text-slate-200">System Architecture</h3>
                        </div>
                        <div className="p-6 bg-slate-950/50 rounded-xl border border-slate-800 overflow-x-auto shadow-inner">
                            <div className="mermaid flex justify-center min-w-[600px]">
                                {mermaidCode}
                            </div>
                        </div>
                    </motion.div>
                )}

                {/* Markdown Content */}
                <div className="prose prose-invert prose-lg max-w-none text-slate-300 prose-headings:text-white prose-a:text-blue-400 prose-strong:text-white prose-code:text-purple-300">
                    <ReactMarkdown components={{
                        h1: ({ node, ...props }) => <h1 className="text-3xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400 mb-6" {...props} />,
                        h2: ({ node, ...props }) => <h2 className="text-2xl font-bold border-l-4 border-blue-500 pl-4 mt-8 mb-4 flex items-center" {...props} />,
                        li: ({ node, ...props }) => <li className="marker:text-blue-500" {...props} />
                    }}>
                        {cleanMarkdown}
                    </ReactMarkdown>
                </div>

                {/* Export Section */}
                <div className="mt-12 pt-8 border-t border-white/5">
                    <h4 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4">Export Options</h4>
                    <ExportTools
                        blueprintRef={blueprintRef}
                        markdownContent={blueprint} // Only export text, not PDF logic yet
                        title={getTitle()}
                    />
                </div>
            </div>

            {/* Deep Dive Modules (Widgets) */}
            {parsedStats && (
                <motion.div
                    initial={{ opacity: 0, y: 40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.5, duration: 0.8 }}
                >
                    <DeepDiveStats stats={parsedStats} />
                </motion.div>
            )}

        </div>
    );
};

export default BlueprintView;
