apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: freelancers-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 0
  selector:
    matchLabels:
      app: freelancers-app
  template:
    metadata:
      labels:
        app: freelancers-app
    spec:
      containers:
      - name: app
        image: IMAGE_PLACEHOLDER_APP
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: freelancers-app
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30050
